### ISSUE TITLE
DaprCon Blog Post

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/blog#83]
## **Details**:
I'd like us to make a blog post to announce that DaprCon is happening this year. I was thinking we could just re-work the [DaprCon announcement content from last year](https://blog.dapr.io/posts/2021/08/31/announcing-daprcon-2021/) and create a new post for this year's conference. 

## **Additional Info:**  
Here's what we sent over to CNCF for this year's conference. This has the updated info for DaprCon 2022

###  **DaprCon**
TUESDAY, OCTOBER 25 | 9:00 AM – 5:00 PM

Join us at DaprCon 2022 and help us celebrate Dapr’s 3rd anniversary as a project! This year as an incubating CNCF project, DaprCon will be hosted as a community day event during KubeCon NA – same great event but with a larger community to share it with!

This year, DaprCon will be a hybrid event allowing everyone to join either in-person at KubeCon or from the comfort of their home or office.

**DaprCon will offer opportunities to:**
- Hear stories and experiences from companies who have integrated Dapr into their solutions.
- Participate in hands-on Dapr technical sessions – code with us or just sit-in and listen.
- Speak to Dapr project maintainers, co-founders and contributors.
- Participate in our end-user panels for Dapr questions on their real scenarios and architectures.
- Discuss stories, learnings, and best practices for Dapr and how it can positively impact cloud native development.

No matter what language you program in, platform you target or architecture setup you leverage, Dapr adds value to your application. Join the community at DaprCon 2022 and stop by during KubeCon to see Dapr in action.

**Registration Fees:** Free

**Comment by msfussell** [comment]
Done
