### ISSUE TITLE
Can't enable Google Analytics 4 because Docsy version is too old

### ISSUE THREAD

**Issue by chalin** [dapr/blog#94]
Subject says it all. This is related to #92.

Tasks:

- [ ] Upgrade docsy. For some discussion about this see the next comment below.
- [ ] Finalize GA4 setup started via #93:
  - [ ] Uncomment GA ID in Hugo config file
  - [ ] Drop `daprblog/layouts/partials/hooks/head-end.html`

/cc @nate-double-u

**Comment by chalin** [comment]
As a first step I'd suggest upgrading to [v0.1.0](https://github.com/google/docsy/releases/tag/v0.1.0). In doing so I've already noticed some local partial overrides that are causing problems, for example, notice how the TOC is misplaced:

> <img width="1633" alt="Screen Shot 2022-11-09 at 11 25 04" src="https://user-images.githubusercontent.com/4140793/200887947-0b3b35aa-a52e-42f4-8941-dcc16a36d76a.png">

It will be some effort to upgrade Docsy to the latest version. It might be worth considering the following first:

- https://github.com/dapr/docs/issues/2948

**Comment by msfussell** [comment]
close
